---
- hosts: localhost
  vars:
    username: sirianni
  become: yes
  pre_tasks:
    - name: Create '{{ username }}' user
      user:
        name: "{{ username }}"
        shell: /bin/zsh
        groups: adm,admin,sudo,audio,video,dip,plugdev,netdev
    - name: Add localhost to /etc/ansible/hosts
      lineinfile:
        dest: /etc/ansible/hosts
        state: present
        regexp: '^localhost'
        line: 'localhost ansible_connection=local'
  roles:
    - sudo
    - ssh_keys
    - dotfiles
